version: '3'
name: steinkamp_dev
services:
  web:
    build:
      context: ..
      target: dev
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ..:/usr/src/app
      - /usr/src/app/public
