version: '3'
name: steinkamp_prod
services:
  web:
    build:
      context: ..
      target: prod
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      JEKYLL_ENV: production
